name: Github page deploy for travel-app

# trigger event
on:
  push: 
    branches:
      - "master"

jobs: 
  build: 
    runs-on: windows-latest

    strategy:
      matrix: 
        node-versio: [15.x]
    
    steps: 
      - name: Checkout
        uses: actions/Checkout@v1 

      - name: Install and build
        run: npm install && npm run build 

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy. 

  
      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BASE_BRANCH: master
      #     BRANCH: gh-pages
      #     FOLDER: website/build
